name: API Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Start API server
        run: npm start &

      - name: Run Playwright tests
        run: npm test

      - name: Upload Playwright reports to S3
        uses: actions/upload-artifact@v2
        with:
          name: playwright-reports
          path: test-results/

      - name: Upload to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws s3 cp test-results/ s3://nikhiltestjava/playwright-reports/ --recursive
        env:
          AWS_REGION: ap-south-1

      - name: Set output for report link
        id: set-output
        run: echo "::set-output name=report_link::https://nikhiltestjava.s3.ap-south-1.amazonaws.com/playwright-reports/" 

      - name: Display report link
        run: echo "Playwright report is available at ${{ steps.set-output.outputs.report_link }}"
